name: Name of Workflow

on: 
  push:
  schedule:
    # 11th minute of the 23rd hour on a Sunday
    - cron: '11 23 * * 0'

permissions: write-all

jobs:
  name-of-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.3' # The R version to download (if necessary) and use.
      - uses: r-lib/actions/setup-renv@v2
      # needs the libcurl library
      - run: sudo apt-get install libcurl4-openssl-dev
      - run: |
          source("script.R")
        shell: Rscript {0}
          

      - name: Commit files
        run: |
          git pull
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add --all
          git commit -am "actions commit"
          git push